sudo: false

language: python

python:
  - "3.7"

install:
  - pip install codecov

env:
  CODECOV_TOKEN="e50770c5-8920-437b-b0e7-41195e30a410"

script:
  - coverage run cps5790test.py

after_success:
  - codecov

deploy:
  provider: s3
  access_key_id: "AWSAccessKeyId=AKIAIYXENBRYLCOV5N3A"
  secret_access_key: "AWSSecretKey=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"
  bucket: "cps847midterm5790"
